//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a T4 template.
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoperAlgoLib.Geometry
{
    public struct PointUInt
    {
        public uint X;
        public uint Y;

        public PointUInt(uint x, uint y)
        {
            X = x;
            Y = y;
        }
    }
}
