//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a T4 template.
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackerCup.Common.Data
{
    public struct PointUInt
    {
        public uint x;
        public uint y;

        public PointUInt(uint x, uint y)
        {
            this.x = x;
            this.y = y;
        }
    }
}
