//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a T4 template.
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackerCup.Common.Data
{
    public struct PointF
    {
        public float x;
        public float y;

        public PointF(float x, float y)
        {
            this.x = x;
            this.y = y;
        }
    }
}
