//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a T4 template.
//
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackerCup.Common.Data
{
    public struct PointD
    {
        public double x;
        public double y;

        public PointD(double x, double y)
        {
            this.x = x;
            this.y = y;
        }
    }
}
